version: "3.9"

services:
  web:
    build:
      context: .
    container_name: mic-main-volume
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: KuIDwvaatQAmdCDRlZoXXdjyeMQdjuxv
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mic_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: KuIDwvaatQAmdCDRlZoXXdjyeMQdjuxv
      MYSQL_DATABASE: railway
    volumes:
      - ./docker/mysql-dump:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: mic_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: KuIDwvaatQAmdCDRlZoXXdjyeMQdjuxv
      MYSQL_ROOT_PASSWORD: KuIDwvaatQAmdCDRlZoXXdjyeMQdjuxv
      UPLOAD_LIMIT: 256M
    ports:
      - "8080:80"
    volumes:
      - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  mysql_data:
